export interface VendorDefinition {
  name: string;
  slug: string;
  email: string;
  businessAddress: string;
  phone: string;
  description: string;
  categories: string[];
}

export const VENDOR_DEFINITIONS: VendorDefinition[] = [
  {
    name: 'Apex Electronics',
    slug: 'apex-electronics',
    email: 'apex@bazaarone.com',
    businessAddress: '42 Silicon Square, Electronic City, Bengaluru, Karnataka - 560100',
    phone: '+91 98765 43210',
    description: 'Specialist in premium consumer electronics, computing gear, cutting-edge audio systems, and smart mobile accessories.',
    categories: ['electronics', 'computers-accessories', 'mobile-accessories'],
  },
  {
    name: 'UrbanCart',
    slug: 'urbancart',
    email: 'urbancart@bazaarone.com',
    businessAddress: '18 Fashion Promenade, Indiranagar, Bengaluru, Karnataka - 560038',
    phone: '+91 98765 43211',
    description: 'Curated apparel, premium organic fabrics, contemporary footwear, and clean botanical personal care essentials.',
    categories: ['mens-fashion', 'womens-fashion', 'beauty-personal-care'],
  },
  {
    name: 'HomeNest',
    slug: 'homenest',
    email: 'homenest@bazaarone.com',
    businessAddress: '88 Green Valley Boulevard, Whitefield, Bengaluru, Karnataka - 560066',
    phone: '+91 98765 43212',
    description: 'Handcrafted kitchenware, artisanal cookware, luxury home textiles, and farm-direct organic grocery delicacies.',
    categories: ['home-kitchen', 'grocery-food'],
  },
  {
    name: 'PlaySphere',
    slug: 'playsphere',
    email: 'playsphere@bazaarone.com',
    businessAddress: '105 Velocity Arena, Koramangala, Bengaluru, Karnataka - 560034',
    phone: '+91 98765 43213',
    description: 'Performance fitness equipment, precision automotive gadgets, STEM robotics, and premium artisanal stationery.',
    categories: ['sports-fitness', 'books-stationery', 'toys-games', 'automotive'],
  },
];

export function getVendorSlugForCategory(categorySlug: string): string {
  const found = VENDOR_DEFINITIONS.find((v) => v.categories.includes(categorySlug));
  return found ? found.slug : 'apex-electronics';
}

export interface CuratedProduct {
  name: string;
  categorySlug: string;
  categoryName: string;
  brandName: string;
  vendorIndex?: number;
  vendorSlug?: string;
  description: string;
  price: number;
  discountPrice?: number;
  stock: number;
  sku: string;
  imageUrl: string;
}

export const CURATED_100_PRODUCTS: CuratedProduct[] = [
  // =========================================================================
  // 1. ELECTRONICS (12 Products) — Target Price Range: ₹2,000 to ₹80,000
  // =========================================================================
  {
    name: 'AuraSound Pro Active Noise Cancelling Headphones',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Industry-leading 45mm dynamic neodymium drivers with hybrid active noise cancellation, 40-hour battery life, and ultra-plush memory foam earcups.',
    price: 21499,
    discountPrice: 17499,
    stock: 25,
    sku: 'ELEC-HP-01',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Horizon Ultra-HD 4K Action Camera 60FPS',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Rugged waterproof 4K action camera with dual color screens, 6-axis electronic image stabilization, and included waterproof housing to 30m.',
    price: 51999,
    discountPrice: 43499,
    stock: 14,
    sku: 'ELEC-CAM-02',
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Vanguard GPS Smart Fitness Watch with AMOLED Display',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Precision heart rate and SpO2 tracking, built-in multi-constellation GPS, 5ATM water resistance, and 14-day battery life on a single charge.',
    price: 33999,
    discountPrice: 28499,
    stock: 30,
    sku: 'ELEC-WTCH-03',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'SonicBoom 360 Portable Waterproof Bluetooth Speaker',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '30W omnidirectional surround sound with dual passive bass radiators, IP67 waterproof and dustproof rating, and 20 hours continuous playtime.',
    price: 6499,
    discountPrice: 4999,
    stock: 40,
    sku: 'ELEC-SPK-04',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'AeroPods True Wireless Earbuds with Wireless Charging Case',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Bluetooth 5.3 earbuds with low latency gaming mode, ENC quad-microphone array for crystal clear calls, and Qi wireless charging case.',
    price: 4999,
    discountPrice: 3499,
    stock: 50,
    sku: 'ELEC-TWS-05',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'CineView 1080p Smart Home Theater Projector',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Native 1080p Full HD projector with 850 ANSI lumens, auto-keystone correction, built-in Android TV OS, and dual 10W stereo speakers.',
    price: 28999,
    discountPrice: 24999,
    stock: 12,
    sku: 'ELEC-PROJ-06',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'PowerVault 20000mAh 65W PD Fast Charging Power Bank',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'High-capacity power bank capable of fast charging laptops and phones simultaneously with dual USB-C Power Delivery and LED power readout.',
    price: 4499,
    discountPrice: 3799,
    stock: 35,
    sku: 'ELEC-PB-07',
    imageUrl: 'https://images.unsplash.com/photo-1609592807908-0112700e1e6f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'SkyScout 4K GPS Foldable Drone with 3-Axis Gimbal',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Foldable quadcopter with 4K UHD stabilized camera, 5km transmission range, intelligent subject tracking, and 31-minute flight time.',
    price: 45999,
    discountPrice: 39999,
    stock: 8,
    sku: 'ELEC-DRN-08',
    imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'NovaPad 10.1 Inch Android Tablet with Active Stylus',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Octa-core 2K IPS display tablet with 128GB storage, quad speakers, 7000mAh battery, and pressure-sensitive pressure pen for artists.',
    price: 19999,
    discountPrice: 16999,
    stock: 20,
    sku: 'ELEC-TAB-09',
    imageUrl: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Clarity Mic Professional USB Studio Condenser Microphone',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Studio-grade 24-bit/192kHz condenser microphone with cardioid pickup pattern, gain control knob, headphone zero-latency monitoring, and pop filter.',
    price: 7999,
    discountPrice: 5999,
    stock: 28,
    sku: 'ELEC-MIC-10',
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Lumina Smart Ambient LED Light Bar Kit with Sync Box',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Dual RGBIC ambient desktop light bars with real-time music rhythm synchronization, smartphone app control, and Alexa/Google Assistant support.',
    price: 3499,
    discountPrice: 2799,
    stock: 45,
    sku: 'ELEC-LGT-11',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'SmartPlug Wi-Fi Energy Monitoring Smart Socket (16A)',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Heavy-duty 16A smart plug with real-time power consumption telemetry, scheduling timers, surge protection, and direct voice assistant pairing.',
    price: 2199,
    discountPrice: 1699,
    stock: 60,
    sku: 'ELEC-PLG-12',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 2. COMPUTERS & ACCESSORIES (8 Products) — Target: ₹500 to ₹1,20,000
  // =========================================================================
  {
    name: 'Apex Mechanical Gaming Keyboard with Hot-Swappable Red Switches',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Compact 75% mechanical keyboard with factory-lubed linear switches, sound dampening foam, per-key RGB backlighting, and detachable coiled aviator cable.',
    price: 6999,
    discountPrice: 5499,
    stock: 35,
    sku: 'COMP-KB-01',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'ErgoGlide Vertical Wireless Ergonomic Optical Mouse',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Natural handshake 57-degree vertical grip design reduces wrist pressure and forearm strain. Features silent clicks and adjustable 4000 DPI sensor.',
    price: 3299,
    discountPrice: 2499,
    stock: 45,
    sku: 'COMP-MS-02',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'UltraDock 12-in-1 Dual 4K HDMI USB-C Docking Station',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Aircraft aluminum multi-display hub with dual HDMI 4K@60Hz, 100W Power Delivery pass-through, Gigabit Ethernet, SD/TF reader, and 4 USB 3.0 ports.',
    price: 8999,
    discountPrice: 7499,
    stock: 22,
    sku: 'COMP-DCK-03',
    imageUrl: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Titan Aluminum Height-Adjustable Ergonomic Laptop Stand',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Solid sandblasted aluminum riser with precision dual-hinge rotation, cooling ventilation cutouts, and anti-slip silicone pads. Supports up to 17-inch laptops.',
    price: 2499,
    discountPrice: 1999,
    stock: 50,
    sku: 'COMP-STD-04',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'StreamCam 2K QHD Autofocus Webcam with Privacy Shutter',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Quad-HD 1440p camera sensor with intelligent auto-exposure, dual noise-cancelling stereo microphones, and 360-degree rotation bracket.',
    price: 4599,
    discountPrice: 3699,
    stock: 30,
    sku: 'COMP-CAM-05',
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'SwiftVault 1TB Portable NVMe External SSD (1050MB/s)',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Pocket-sized rugged external solid state drive with USB 3.2 Gen 2 interface, drop-resistant silicone bumper, and hardware-level AES 256-bit encryption.',
    price: 8499,
    discountPrice: 6999,
    stock: 40,
    sku: 'COMP-SSD-06',
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'NetMax Pro Wi-Fi 6 Dual-Band Gigabit Mesh Router',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Ultra-fast AX3000 speeds with OFDMA, MU-MIMO technology, 4 high-gain antennas, and seamless whole-home mesh coverage up to 3,000 sq ft.',
    price: 6499,
    discountPrice: 4999,
    stock: 22,
    sku: 'COMP-RTR-07',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'ChromaGlide Extended Desk Mat XXL Gaming Mouse Pad',
    categorySlug: 'computers-accessories',
    categoryName: 'Computers & Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '900x400mm waterproof micro-textured cloth gaming surface with non-slip natural rubber base and anti-fray reinforced stitched edges.',
    price: 1299,
    discountPrice: 999,
    stock: 65,
    sku: 'COMP-PAD-08',
    imageUrl: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 3. MEN'S FASHION (8 Products) — Target: ₹400 to ₹5,000
  // =========================================================================
  {
    name: 'Artisan Heritage Pure French Linen Casual Shirt',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Woven from 100% natural European flax linen, breathable relaxed fit with natural shell buttons, mandarin collar, and pre-washed softness.',
    price: 3099,
    discountPrice: 2499,
    stock: 40,
    sku: 'MEN-SHRT-01',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Selvedge Slim-Fit Raw Denim Jeans (14oz)',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Authentic 14oz shuttle-loom selvedge denim in rich indigo dye, reinforced copper rivets, tailored slim tapered fit that patinas uniquely over time.',
    price: 3799,
    discountPrice: 2999,
    stock: 30,
    sku: 'MEN-JN-02',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handcrafted Full-Grain Leather Oxford Dress Shoes',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Burnished cognac full-grain cowhide leather with Goodyear welted construction, cushioned leather insole, and hand-finished closed lace styling.',
    price: 4899,
    discountPrice: 3899,
    stock: 18,
    sku: 'MEN-SHOE-03',
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Classic Supima Cotton Crewneck Henley T-Shirt',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Long-staple organic Supima cotton jersey with a 3-button placket, ribbed cuffs, breathable moisture-wicking feel, and fade-resistant dye.',
    price: 1499,
    discountPrice: 1199,
    stock: 60,
    sku: 'MEN-HNLY-04',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Aviator Polarized Titanium Sunglasses',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Ultra-lightweight aerospace titanium frame with scratch-resistant polarized TAC lenses offering 100% UV400 solar protection and silicone nose pads.',
    price: 2999,
    discountPrice: 2299,
    stock: 35,
    sku: 'MEN-SUN-05',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pure Merino Wool V-Neck Pullover Sweater',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Finely spun 100% Australian Merino wool offering natural temperature regulation, featherlight softness without itch, and ribbed hem details.',
    price: 3499,
    discountPrice: 2799,
    stock: 25,
    sku: 'MEN-SWTR-06',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Heritage Full-Grain Leather Bifold RFID Wallet',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Vegetable-tanned saddle leather wallet with 8 card slots, dual currency compartments, quick-access ID window, and built-in RFID blocking shield.',
    price: 1899,
    discountPrice: 1399,
    stock: 50,
    sku: 'MEN-WLT-07',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Waxed Canvas & Leather Weekender Duffle Bag',
    categorySlug: 'mens-fashion',
    categoryName: "Men's Fashion",
    brandName: 'Urban Stitch',
    vendorIndex: 1,
    description: 'Heavyweight 18oz water-repellent waxed canvas with oil-tanned leather handles, solid brass hardware, shoe compartment, and 45L travel capacity.',
    price: 4599,
    discountPrice: 3699,
    stock: 15,
    sku: 'MEN-BAG-08',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 4. WOMEN'S FASHION (10 Products) — Target: ₹500 to ₹8,000
  // =========================================================================
  {
    name: 'Handloom Pure Mulberry Silk Zari Embroidered Saree',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Woven on traditional pit-looms in Varanasi with pure mulberry silk yarn, intricate gold zari floral brocade border, and included unstitched matching blouse piece.',
    price: 7999,
    discountPrice: 5999,
    stock: 20,
    sku: 'WOM-SAR-01',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Floral Chiffon Tiered Summer Maxi Dress',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Flowing breathable georgette chiffon with delicate botanical print, elasticated smocked bodice, ruffled tiered skirt, and soft cotton inner lining.',
    price: 2899,
    discountPrice: 2199,
    stock: 35,
    sku: 'WOM-DRS-02',
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handcrafted Structured Leather Shoulder Tote Bag',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Premium Italian calf leather with gold-tone hardware, padded 14-inch laptop sleeve, internal zip organizers, and reinforced double shoulder straps.',
    price: 6499,
    discountPrice: 4999,
    stock: 18,
    sku: 'WOM-BAG-03',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pure Chanderi Cotton Silk Embroidered Kurti Set',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Three-piece ethnic ensemble featuring a straight-cut Chanderi kurti with hand-embroidered mirrorwork, comfortable palazzo pants, and organza dupatta.',
    price: 3999,
    discountPrice: 2999,
    stock: 28,
    sku: 'WOM-KRT-04',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pure Cashmere Pashmina Stole Wrap with Fringe Hem',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Exquisitely hand-spun Grade-A Himalayan cashmere offering weightless warmth, cloud-like drape, hand-rolled fringed edges, and timeless elegance.',
    price: 5499,
    discountPrice: 4299,
    stock: 22,
    sku: 'WOM-STL-05',
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handcrafted Suede Leather Block Heel Ankle Boots',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Velvety genuine suede with a comfortable 2.5-inch stacked wooden block heel, side zip closure, cushioned arch support, and non-slip rubber outsole.',
    price: 4799,
    discountPrice: 3699,
    stock: 20,
    sku: 'WOM-BOT-06',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '925 Sterling Silver Cubic Zirconia Drop Earrings',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Hypoallergenic rhodium-plated 925 sterling silver with brilliant teardrop cut cubic zirconia stones and secure French wire backing.',
    price: 2199,
    discountPrice: 1599,
    stock: 45,
    sku: 'WOM-JWL-07',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Vintage Wash Distressed Denim Trucker Jacket',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Mid-weight 100% cotton denim in a classic relaxed trucker silhouette with button flap chest pockets, adjustable waist tabs, and vintage fade.',
    price: 3299,
    discountPrice: 2499,
    stock: 30,
    sku: 'WOM-JCK-08',
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handwoven Jute & Vegan Leather Evening Clutch',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Eco-friendly natural woven jute accented with soft vegan leather trim, magnetic snap closure, detachable gold chain strap, and interior card slots.',
    price: 1799,
    discountPrice: 1299,
    stock: 40,
    sku: 'WOM-CLT-09',
    imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Memory Foam Padded Leather Ballet Flats',
    categorySlug: 'womens-fashion',
    categoryName: "Women's Fashion",
    brandName: 'Artisan Loom',
    vendorIndex: 2,
    description: 'Ultra-flexible butter-soft nappa leather ballet flats with 6mm high-density memory foam footbed and elasticized topline for blister-free comfort.',
    price: 2599,
    discountPrice: 1999,
    stock: 35,
    sku: 'WOM-FLT-10',
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 5. HOME & KITCHEN (12 Products) — Target: ₹300 to ₹15,000
  // =========================================================================
  {
    name: 'Pre-Seasoned Heavy-Duty Cast Iron Skillet (10.5 Inch)',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Hand-cast virgin iron skillet pre-seasoned with 100% natural organic flaxseed oil. Superior heat retention with dual pour spouts and helper handle.',
    price: 3299,
    discountPrice: 2499,
    stock: 45,
    sku: 'HOME-SKL-01',
    imageUrl: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hand-Thrown Matte Ceramic Dinnerware Set (16 Pieces)',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Artisanal stoneware set for 4 (dinner plates, salad plates, soup bowls, mugs) finished with reactive slate gray glaze. Microwave and dishwasher safe.',
    price: 7499,
    discountPrice: 5999,
    stock: 15,
    sku: 'HOME-DNW-02',
    imageUrl: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '15-Bar Italian Pump Stainless Steel Espresso Machine',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'High-pressure 15-bar Italian extraction system with thermo-block fast heating, swivel steam wand for silky micro-foam, and dual cup portafilter.',
    price: 13999,
    discountPrice: 11499,
    stock: 12,
    sku: 'HOME-ESP-03',
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '400 Thread Count 100% Egyptian Cotton Bedsheet Set',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'King size luxury sateen weave sheet set with deep pocket elastic fitted sheet, flat sheet, and two king pillowcases. Silky smooth and breathable.',
    price: 4999,
    discountPrice: 3899,
    stock: 25,
    sku: 'HOME-BED-04',
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handcrafted Sheesham Wood Traditional Spice Box with Glass Lid',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Solid Indian rosewood masala dabba with 9 removable spice containers, brass latch lock, glass display window, and handmade wooden spice spoon.',
    price: 2199,
    discountPrice: 1699,
    stock: 35,
    sku: 'HOME-SPC-05',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Digital Air Fryer with Rapid 360 Air Convection (5.5L)',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: '1700W oil-free air fryer with 8 one-touch preset cooking modes, intuitive LED touch panel, non-stick dishwasher-safe fry basket, and recipe book.',
    price: 7999,
    discountPrice: 6299,
    stock: 20,
    sku: 'HOME-AFR-06',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ergonomic Cervical Contour Memory Foam Pillow',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Orthopedic butterfly contour design aligns neck and spine for side and back sleepers. Includes breathable cooling bamboo fiber zippered pillow cover.',
    price: 2799,
    discountPrice: 1999,
    stock: 40,
    sku: 'HOME-PLW-07',
    imageUrl: 'https://images.unsplash.com/photo-1629949009765-40fc74c9521b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Handcrafted High-Carbon German Steel 8-Inch Chef Knife',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Precision forged DIN 1.4116 German steel blade hand-sharpened to 15 degrees per side with ergonomic pakkawood handle and protective sheath.',
    price: 3899,
    discountPrice: 2999,
    stock: 30,
    sku: 'HOME-KNF-08',
    imageUrl: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Artisan Hand-Tufted 100% New Zealand Wool Area Rug (5x7 Ft)',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Heavy plush 0.75-inch pile wool rug featuring Scandinavian minimalist geometric motifs, natural non-slip canvas backing, and stain resistance.',
    price: 12499,
    discountPrice: 9999,
    stock: 10,
    sku: 'HOME-RUG-09',
    imageUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pure Soy Wax Aromatherapy Scented Candle in Ceramic Jar',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Hand-poured 300g soy candle with pure French lavender and cedarwood essential oils, crackling wooden wick, and 60-hour clean non-toxic burn time.',
    price: 1499,
    discountPrice: 1099,
    stock: 50,
    sku: 'HOME-CNDL-10',
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Stainless Steel Gravity-Fed Countertop Water Purifier (12L)',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Dual-chamber food-grade 304 stainless steel gravity system with dual micro-porous activated carbon ceramic candles. Requires no electricity.',
    price: 5999,
    discountPrice: 4799,
    stock: 18,
    sku: 'HOME-WTR-11',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Heavy-Duty 1200W Commercial Blender & Food Processor',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: '28000 RPM high-torque motor with 6 hardened stainless steel blades, 2L BPA-free tritan pitcher, variable speed dial, and pulse crushing function.',
    price: 8999,
    discountPrice: 7199,
    stock: 15,
    sku: 'HOME-BLND-12',
    imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 6. BEAUTY & PERSONAL CARE (8 Products) — Target: ₹200 to ₹5,000
  // =========================================================================
  {
    name: '2% Pure Hyaluronic Acid & B5 Deep Hydration Serum (30ml)',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Multi-molecular weight hyaluronic acid formula penetrating deep skin layers to plump and retain moisture with soothing Provitamin B5.',
    price: 999,
    discountPrice: 799,
    stock: 60,
    sku: 'BEAU-SRM-01',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Cold-Pressed Moroccan Argan Oil Pure Botanical Extract (100ml)',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: '100% certified organic unrefined argan oil packed with Vitamin E and essential fatty acids for hair frizz control and radiant skin restoration.',
    price: 1299,
    discountPrice: 999,
    stock: 45,
    sku: 'BEAU-OIL-02',
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-07f28ecb3c43?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sulfate-Free Onion & Bhringraj Anti-Hairfall Shampoo (300ml)',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Traditional Ayurvedic formulation enriched with red onion seed extract and plant keratin to strengthen roots and reduce hair breakage.',
    price: 899,
    discountPrice: 699,
    stock: 50,
    sku: 'BEAU-SHMP-03',
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Broad Spectrum SPF 50 PA++++ Invisible Matte Sunscreen Gel (50g)',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Ultra-lightweight oil-free sunscreen gel leaving zero white cast. Formulated with Cica and Niacinamide for non-greasy all-day protection.',
    price: 749,
    discountPrice: 599,
    stock: 70,
    sku: 'BEAU-SUN-04',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'All-Natural Cedarwood & Sandalwood Beard Grooming Kit',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Complete men care box including organic beard growth oil, conditioning styling balm, anti-static peach wood dual-teeth comb, and boar bristle brush.',
    price: 1899,
    discountPrice: 1499,
    stock: 35,
    sku: 'BEAU-BRD-05',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Velvet Matte Long-Lasting Hydrating Lipstick Collection',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Transfer-proof 12-hour matte finish enriched with jojoba seed oil and shea butter to prevent feathering while delivering intense color payoff.',
    price: 1199,
    discountPrice: 899,
    stock: 55,
    sku: 'BEAU-LP-06',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'French Green Clay & Matcha Purifying Detox Face Mask (100g)',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: 'Mineral-rich Montmorillonite clay infused with ceremonial Japanese matcha to draw out impurities, refine pore appearance, and brighten dull skin.',
    price: 999,
    discountPrice: 799,
    stock: 40,
    sku: 'BEAU-MSK-07',
    imageUrl: 'https://images.unsplash.com/photo-1567928815104-b6770f3f61b9?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sonic Rechargeable Electric Toothbrush with 4 Brush Heads',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Botanica Herbal',
    vendorIndex: 4,
    description: '40000 micro-vibrations per minute with 5 intelligent cleaning modes, built-in 2-minute smart timer, IPX7 waterproofing, and 60-day USB battery life.',
    price: 2499,
    discountPrice: 1899,
    stock: 30,
    sku: 'BEAU-TBR-08',
    imageUrl: 'https://images.unsplash.com/photo-1559591937-e10b1a03975c?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 7. GROCERY & FOOD (10 Products) — Target: ₹50 to ₹3,000
  // =========================================================================
  {
    name: 'Organic Certified Single-Origin Kashmir Mongra Saffron (1g)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Grade-A1 pure all-red stigma filaments hand-harvested from Pampore valley. High safranal aroma and intense natural golden color for royal delicacies.',
    price: 1999,
    discountPrice: 1699,
    stock: 40,
    sku: 'GROC-SAF-01',
    imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Raw Unfiltered Wild Forest Honey (500g Glass Jar)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Sustainably collected from wild multi-floral beehives in dense Corbett forests. Unheated, unpasteurized, and naturally rich in active bee pollen enzymes.',
    price: 899,
    discountPrice: 699,
    stock: 50,
    sku: 'GROC-HNY-02',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Wood-Pressed Traditional Vedic A2 Gir Cow Ghee (1 Litre)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Crafted using the authentic Bilona method from grass-fed indigenous Gir cow curd. Rich golden granular texture with divine nutty aroma.',
    price: 2499,
    discountPrice: 2099,
    stock: 35,
    sku: 'GROC-GHE-03',
    imageUrl: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Single-Estate 100% Arabica Dark Roast Coffee Beans (500g)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Shade-grown high-altitude Arabica beans from Chikmagalur hills, slow roasted in small batches with notes of dark cocoa, roasted hazelnut, and caramel.',
    price: 949,
    discountPrice: 799,
    stock: 60,
    sku: 'GROC-COF-04',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Royal Heritage CTC Black Tea with Fresh Cardamom (250g Tin)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'First flush robust Assam CTC tea leaves blended with aromatic crushed green cardamom pods from Idukki for a rich, full-bodied morning brew.',
    price: 549,
    discountPrice: 429,
    stock: 65,
    sku: 'GROC-TEA-05',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pure Himalayan Mineral Pink Rock Salt Coarse Crystals (1kg)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Unrefined, unbleached ancient rock salt mined from the Himalayan foothills, rich in 84 natural trace minerals for culinary seasoning.',
    price: 349,
    discountPrice: 249,
    stock: 80,
    sku: 'GROC-SLT-06',
    imageUrl: 'https://images.unsplash.com/photo-1626078436573-0ffaa7452d5b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Extra Virgin Wood-Pressed Cold-Pressed Coconut Oil (500ml)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Extracted in wooden Chekku presses from sun-dried Kerala copra without chemical heat, preserving natural lauric acid and fresh coconut flavor.',
    price: 499,
    discountPrice: 389,
    stock: 55,
    sku: 'GROC-COC-07',
    imageUrl: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '72% Single-Origin Artisanal Bean-to-Bar Dark Chocolate (80g)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Crafted from ethically sourced single-origin Idukki cacao beans and organic unrefined cane sugar with tasting notes of wild berries and espresso.',
    price: 399,
    discountPrice: 299,
    stock: 75,
    sku: 'GROC-CHC-08',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Premium Jumbo California Raw Almonds & Walnut Kernels Combo (500g)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: 'Vacuum-sealed air-tight container of crunchy Nonpareil whole almonds and Kashmiri walnut halves rich in Omega-3 fatty acids and plant protein.',
    price: 1199,
    discountPrice: 949,
    stock: 45,
    sku: 'GROC-NUT-09',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Organic Gluten-Free Whole Grain Rolled Oats (1kg)',
    categorySlug: 'grocery-food',
    categoryName: 'Grocery & Food',
    brandName: 'Himalayan Harvest',
    vendorIndex: 5,
    description: '100% whole grain jumbo rolled oats with soluble beta-glucan fiber, zero preservatives, and ideal thick-cut texture for oatmeal bowls and baking.',
    price: 449,
    discountPrice: 349,
    stock: 60,
    sku: 'GROC-OAT-10',
    imageUrl: 'https://images.unsplash.com/photo-1586439702132-42171587593c?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 8. SPORTS & FITNESS (7 Products) — Target: ₹300 to ₹15,000
  // =========================================================================
  {
    name: 'Quick-Select Adjustable Dumbbell Pair (2.5kg to 24kg)',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Compact 15-in-1 home gym weight system with rapid mechanical selector dial, textured knurled steel grip handle, and heavy-duty storage base trays.',
    price: 13999,
    discountPrice: 11499,
    stock: 12,
    sku: 'SPRT-DMB-01',
    imageUrl: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Extra Thick 8mm Eco-Friendly TPE Alignment Yoga Mat',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'High-density dual-layer textured non-slip surface with laser-engraved body alignment lines, superior joint cushioning, and complimentary carrying strap.',
    price: 2499,
    discountPrice: 1899,
    stock: 40,
    sku: 'SPRT-MAT-02',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Double-Wall Vacuum Insulated Stainless Steel Sports Bottle (1000ml)',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '18/8 food-grade pro stainless steel bottle keeps drinks ice-cold for 24 hours or piping hot for 12 hours with leakproof magnetic chug cap.',
    price: 1399,
    discountPrice: 999,
    stock: 55,
    sku: 'SPRT-BTL-03',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Premium Non-Slip Fabric Booty Resistance Loop Bands (Set of 3)',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Durable cotton-latex blend exercise bands that will not roll or pinch skin during glute, leg, and mobility workouts. 3 graduated resistance levels.',
    price: 1199,
    discountPrice: 849,
    stock: 60,
    sku: 'SPRT-BND-04',
    imageUrl: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'High-Speed Ball Bearing Adjustable Steel Cable Jump Rope',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '360-degree dual ball bearing mechanism delivering smooth, tangle-free rotations for double-unders with silicone coated lightweight aluminum handles.',
    price: 899,
    discountPrice: 649,
    stock: 50,
    sku: 'SPRT-JMP-05',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'High-Density Trigger Point Deep Tissue Foam Roller (18 Inch)',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Multi-density grid matrix mimics a massage therapist hands to relieve muscle soreness, increase blood circulation, and accelerate post-workout recovery.',
    price: 1699,
    discountPrice: 1299,
    stock: 35,
    sku: 'SPRT-RLR-06',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Padded Leather Weightlifting Gloves with Built-in Wrist Wraps',
    categorySlug: 'sports-fitness',
    categoryName: 'Sports & Fitness',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Genuine goat leather palm with silicone honeycomb grip padding, breathable mesh backing, and 18-inch adjustable elastic wrist support wraps.',
    price: 1499,
    discountPrice: 1099,
    stock: 45,
    sku: 'SPRT-GLV-07',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 9. BOOKS & STATIONERY (7 Products) — Target: ₹100 to ₹2,500
  // =========================================================================
  {
    name: 'Handmade Vegan Leather Hardcover Dotted Journal (160 GSM)',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: '192 pages of bleed-resistant 160 GSM ultra-thick bamboo paper, 5mm dotted grid layout, lay-flat thread binding, ribbon bookmark, and back pocket.',
    price: 1299,
    discountPrice: 999,
    stock: 50,
    sku: 'BOK-JRN-01',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Vintage Solid Brass Fine Nib Fountain Pen with Wooden Gift Box',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Precision-machined raw brass pen body that develops a unique aged patina over time, stainless steel Iridium fine nib, and included piston ink converter.',
    price: 1799,
    discountPrice: 1399,
    stock: 30,
    sku: 'BOK-PEN-02',
    imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Executive Undated Daily Productivity Planner & Goal Tracker',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Science-backed 6-month goal breakdown system featuring daily time-blocking schedules, weekly review reflection prompts, and habit habit trackers.',
    price: 1499,
    discountPrice: 1099,
    stock: 45,
    sku: 'BOK-PLN-03',
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Professional Artist Grade 36-Color Watercolor Half-Pan Tin Set',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'High-pigment lightfast watercolor cakes with exceptional transparency and blending capability. Housed in a travel metal tin with fold-out mixing palette.',
    price: 2199,
    discountPrice: 1699,
    stock: 25,
    sku: 'BOK-ART-04',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sustainable Solid Bamboo Multi-Compartment Desk Organizer',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Natural organic bamboo caddy with 6 compartments for pens, stationery accessories, sticky notes, and a built-in angled smartphone docking slot.',
    price: 1399,
    discountPrice: 999,
    stock: 40,
    sku: 'BOK-ORG-05',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dual-Tip Acrylic Paint Marker Pens Set of 24 Colors',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Water-based opaque acrylic ink markers with flexible brush tip and 0.7mm extra-fine tip for drawing on wood, canvas, ceramic, glass, and rock art.',
    price: 1699,
    discountPrice: 1299,
    stock: 35,
    sku: 'BOK-MRK-06',
    imageUrl: 'https://images.unsplash.com/photo-1580569214296-5cf2ebd6ae30?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hand-Lettering & Modern Calligraphy Starter Kit with Oblique Holder',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Complete copperplate calligraphy set including ergonomic wooden pen holder, 5 assorted Nikko/Brause nibs, Japanese sumi black ink, and workbook.',
    price: 1899,
    discountPrice: 1449,
    stock: 20,
    sku: 'BOK-CAL-07',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 10. TOYS & GAMES (6 Products) — Target: ₹200 to ₹5,000
  // =========================================================================
  {
    name: 'Hand-Carved Wooden Tournament Chess Set with Folding Board',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: '15-inch solid Sheesham and Boxwood folding board with weighted Staunton chessmen, felted bases, and internal velvet storage slots for all pieces.',
    price: 3899,
    discountPrice: 2899,
    stock: 25,
    sku: 'TOY-CHS-01',
    imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ancient World Wonder 1000-Piece Jigsaw Puzzle for Adults',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Precision die-cut recycled blueboard puzzle with glare-free matte finish, interlocking zero-dust pieces, and included full-size reference poster.',
    price: 1299,
    discountPrice: 949,
    stock: 40,
    sku: 'TOY-PZL-02',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '14-in-1 Solar Powered Educational STEM Robotics Kit',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Green energy building kit allowing children to assemble 14 different motorized robotic models moving on land or water without requiring batteries.',
    price: 2499,
    discountPrice: 1899,
    stock: 35,
    sku: 'TOY-RBT-03',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Classic Giant Hardwood Tumbling Timber Tower Game',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: '54 precision-cut premium New Zealand pine blocks that build a 3-foot starting tower and can stack over 5 feet high. Includes heavy-duty canvas zip bag.',
    price: 2799,
    discountPrice: 2199,
    stock: 20,
    sku: 'TOY-TWR-04',
    imageUrl: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '3D Magnetic Building Tiles Creativity Set (100 Pieces)',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Vibrant translucent geometric magnetic tiles with food-grade ABS plastic, reinforced ultrasonic welding, and strong neodymium magnets for 3D architecture.',
    price: 3499,
    discountPrice: 2699,
    stock: 30,
    sku: 'TOY-MAG-05',
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Fast-Track Wooden Sling Puck Tabletop Board Game',
    categorySlug: 'toys-games',
    categoryName: 'Toys & Games',
    brandName: 'Nordic Craft',
    vendorIndex: 3,
    description: 'Action-packed 2-player reflex game crafted from solid birch wood with elastic band shooters. Fast-paced fun for family game nights.',
    price: 1699,
    discountPrice: 1249,
    stock: 45,
    sku: 'TOY-SLG-06',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 11. AUTOMOTIVE (6 Products) — Target: ₹300 to ₹10,000
  // =========================================================================
  {
    name: 'Smart 150 PSI Digital Cordless Tire Inflator & Air Pump',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Rechargeable 6000mAh battery portable tire inflator with real-time digital LCD pressure gauge, auto-shutoff safety, and bright emergency LED flashlight.',
    price: 3499,
    discountPrice: 2699,
    stock: 40,
    sku: 'AUTO-INF-01',
    imageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dual-Lens 4K Front + 1080p Rear Dash Camera with Night Vision',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Ultra-HD Sony Starvis sensor with 170-degree wide angle lens, built-in G-sensor collision detection, 24-hour parking monitor, and loop recording.',
    price: 7999,
    discountPrice: 6299,
    stock: 22,
    sku: 'AUTO-DSH-02',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Universal Magnetic Air Vent Car Phone Mount with 360 Rotation',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '6 powerful N52 neodymium magnets hold heavy smartphones firmly across bumpy roads without blocking air vent airflow. Features twist-lock grip clip.',
    price: 899,
    discountPrice: 599,
    stock: 75,
    sku: 'AUTO-MNT-03',
    imageUrl: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'High-Power 120W Cordless Handheld Car Vacuum Cleaner',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: '9000PA strong cyclonic suction with washable HEPA filtration, crevice tool nozzle, dust brush, and USB-C fast charging 4000mAh battery.',
    price: 2499,
    discountPrice: 1899,
    stock: 35,
    sku: 'AUTO-VAC-04',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ultra-Plush 800 GSM Microfiber Car Drying & Detailing Towels (Pack of 3)',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Silk-banded edgeless dual-pile microfiber towels absorbing 10x their weight in water for scratch-free, swirl-free, lint-free vehicle drying.',
    price: 1199,
    discountPrice: 849,
    stock: 60,
    sku: 'AUTO-TWL-05',
    imageUrl: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dual USB-C 85W Fast Car Charger Adapter with Voltage Display',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Full zinc alloy body with 65W PD Type-C and 20W QC3.0 ports. Safely charges MacBook and iPad simultaneously with real-time battery voltage LED readout.',
    price: 1499,
    discountPrice: 1099,
    stock: 50,
    sku: 'AUTO-CHG-06',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
  },

  // =========================================================================
  // 12. MOBILE ACCESSORIES (6 Products) — Target: ₹100 to ₹5,000
  // =========================================================================
  {
    name: 'MagSafe Compatible European Full-Grain Leather Phone Case',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Precision molded genuine top-grain cowhide leather with integrated neodymium magnetic ring for snap-on MagSafe wireless chargers and accessories.',
    price: 2499,
    discountPrice: 1899,
    stock: 55,
    sku: 'MOB-CAS-01',
    imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '65W GaN Fast Wall Charger with Dual USB-C & USB-A Ports',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Gallium Nitride technology delivering 65W high-speed charging in a 50% smaller footprint with foldable US/UK/EU plug adapters and multi-protection safety.',
    price: 2699,
    discountPrice: 2099,
    stock: 45,
    sku: 'MOB-CHG-02',
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Heavy-Duty Braided Nylon USB-C to USB-C 100W Fast Cable (2M)',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'E-Marker chip supporting 100W 20V/5A power delivery and 480Mbps data transfer, double-braided ballistic nylon jacket tested for 30000+ bends.',
    price: 999,
    discountPrice: 749,
    stock: 80,
    sku: 'MOB-CBL-03',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '3-in-1 Foldable Magnetic Wireless Charging Station for Desk',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Simultaneously fast-charges phone (15W), smartwatch (5W), and wireless earbuds (5W) in a travel-ready foldable stand design with soft-touch silicone.',
    price: 3499,
    discountPrice: 2699,
    stock: 30,
    sku: 'MOB-STN-04',
    imageUrl: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '9H Hardness Edge-to-Edge HD Tempered Glass Screen Protector (2-Pack)',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Ultra-thin 0.33mm Japanese Asahi glass with 99.9% optical transparency, oleophobic anti-fingerprint coating, and included auto-alignment frame.',
    price: 699,
    discountPrice: 499,
    stock: 90,
    sku: 'MOB-GLS-05',
    imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: '10-Inch LED Desktop Ring Light with Tripod Stand & Phone Holder',
    categorySlug: 'mobile-accessories',
    categoryName: 'Mobile Accessories',
    brandName: 'Apex Audio',
    vendorIndex: 0,
    description: 'Dimmable USB-powered ring light with 3 color temperature modes (3000K-6000K), 10 brightness levels, 360-degree ball head, and wireless Bluetooth camera remote.',
    price: 1899,
    discountPrice: 1399,
    stock: 40,
    sku: 'MOB-RNG-06',
    imageUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=800&q=80',
  },
];
