import { prisma } from '../config/db';
import { hashPassword } from '../utils/password';
import { PexelsService } from './pexels.service';
import { CloudinaryService } from './cloudinary.service';

export interface SeedProductDefinition {
  name: string;
  categoryName: string;
  categorySlug: string;
  categoryKey: string;
  brandName: string;
  vendorIndex: number;
  description: string;
  price: number;
  discountPrice?: number;
  stock: number;
  sku: string;
  searchQuery: string;
}

export class SeedService {
  /**
   * Complete 100-Product Definition Array across the 12 exact categories
   */
  static get100ProductDefinitions(): SeedProductDefinition[] {
    const products: SeedProductDefinition[] = [
      // ----------------------------------------------------
      // 1. Electronics (12 products)
      // ----------------------------------------------------
      {
        name: 'AuraSound Pro Active Noise Cancelling Headphones',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Industry-leading 45mm dynamic neodymium drivers with hybrid active noise cancellation, 40-hour battery life, and ultra-plush memory foam earcups.',
        price: 8999,
        discountPrice: 6999,
        stock: 25,
        sku: 'ELEC-HP-01',
        searchQuery: 'wireless headphones audio',
      },
      {
        name: 'Horizon Ultra-HD 4K Action Camera 60FPS',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Rugged waterproof 4K action camera with dual color screens, 6-axis electronic image stabilization, and included waterproof housing to 30m.',
        price: 11999,
        discountPrice: 9499,
        stock: 14,
        sku: 'ELEC-CAM-02',
        searchQuery: 'action camera 4k',
      },
      {
        name: 'Vanguard GPS Smart Fitness Watch with AMOLED Display',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Precision heart rate and SpO2 tracking, built-in multi-constellation GPS, 5ATM water resistance, and 14-day battery life on a single charge.',
        price: 5499,
        discountPrice: 4299,
        stock: 30,
        sku: 'ELEC-WTCH-03',
        searchQuery: 'smartwatch fitness',
      },
      {
        name: 'SonicBoom 360 Portable Waterproof Bluetooth Speaker',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '30W omnidirectional surround sound with dual passive bass radiators, IP67 waterproof and dustproof rating, and 20 hours continuous playtime.',
        price: 3499,
        discountPrice: 2799,
        stock: 40,
        sku: 'ELEC-SPK-04',
        searchQuery: 'portable bluetooth speaker',
      },
      {
        name: 'AeroPods True Wireless Earbuds with Wireless Charging',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Bluetooth 5.3 earbuds with low latency gaming mode, ENC quad-microphone array for crystal clear calls, and Qi wireless charging case.',
        price: 2999,
        discountPrice: 2199,
        stock: 50,
        sku: 'ELEC-TWS-05',
        searchQuery: 'wireless earbuds case',
      },
      {
        name: 'Lumix Beam 1080p Full HD Portable Home Projector',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Compact 800 ANSI lumen home cinema projector with auto keystone correction, dual 5W stereo speakers, and HDMI/Wi-Fi screen mirroring.',
        price: 16999,
        discountPrice: 13999,
        stock: 10,
        sku: 'ELEC-PRJ-06',
        searchQuery: 'home cinema projector',
      },
      {
        name: 'PowerCore 26800mAh 65W PD Laptop Power Bank',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'High-capacity airline-safe power bank capable of charging MacBooks, laptops, and smartphones simultaneously with triple fast-charging ports.',
        price: 4599,
        discountPrice: 3899,
        stock: 35,
        sku: 'ELEC-PB-07',
        searchQuery: 'power bank charger',
      },
      {
        name: 'SkyHawk 4K Quadcopter Drone with Optical Flow',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Foldable lightweight drone featuring 3-axis motorized gimbal 4K camera, 32-minute flight time per battery, and auto return-to-home GPS.',
        price: 24999,
        discountPrice: 19999,
        stock: 8,
        sku: 'ELEC-DRN-08',
        searchQuery: 'quadcopter drone',
      },
      {
        name: 'PaperInk 7.8-Inch Glare-Free E-Reader with Warm Light',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '300 PPI Carta electronic paper display with adjustable warm and cool amber front light, 32GB storage, and weeks of battery life.',
        price: 13499,
        discountPrice: 11999,
        stock: 18,
        sku: 'ELEC-ERD-09',
        searchQuery: 'ereader digital book',
      },
      {
        name: 'Nova RGB Studio Microphone for Streaming & Podcasting',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Cardioid condenser studio USB microphone with tap-to-mute sensor, customizable dynamic RGB lighting, and internal pop filter.',
        price: 4999,
        discountPrice: 3999,
        stock: 22,
        sku: 'ELEC-MIC-10',
        searchQuery: 'studio condenser microphone',
      },
      {
        name: 'SmartLife Wi-Fi Smart Plug with Energy Monitoring (4-Pack)',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '16A high-power smart plug compatible with Alexa and Google Assistant with schedule timers and real-time energy kilowatt consumption tracking.',
        price: 2199,
        discountPrice: 1799,
        stock: 45,
        sku: 'ELEC-PLG-11',
        searchQuery: 'smart home plug',
      },
      {
        name: 'VisionGuard 2K Pan-Tilt Indoor Wi-Fi Security Camera',
        categoryName: 'Electronics',
        categorySlug: 'electronics',
        categoryKey: 'electronics',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '360-degree coverage security camera with AI human detection, enhanced color night vision, and two-way real-time audio intercom.',
        price: 2699,
        discountPrice: 1999,
        stock: 30,
        sku: 'ELEC-CAM-12',
        searchQuery: 'security camera smart',
      },

      // ----------------------------------------------------
      // 2. Computers & Accessories (8 products)
      // ----------------------------------------------------
      {
        name: 'Apex Mechanical Keyboard with Hot-Swappable Red Switches',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Tenkeyless 87-key aluminum body mechanical keyboard with pre-lubed linear red switches, PBT double-shot keycaps, and south-facing RGB.',
        price: 4299,
        discountPrice: 3499,
        stock: 28,
        sku: 'COMP-KB-01',
        searchQuery: 'mechanical keyboard rgb',
      },
      {
        name: 'ErgoGlide Vertical Wireless Ergonomic Mouse',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '57-degree natural handshake angle ergonomic vertical mouse to reduce forearm strain, featuring 4000 DPI sensor and dual Bluetooth/2.4G wireless.',
        price: 2299,
        discountPrice: 1799,
        stock: 35,
        sku: 'COMP-MS-02',
        searchQuery: 'ergonomic computer mouse',
      },
      {
        name: 'UltraDock 12-in-1 Dual 4K HDMI USB-C Hub Docking Station',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Universal aluminum docking hub supporting dual 4K monitors, 100W Power Delivery, Gigabit Ethernet, SD card slots, and high-speed USB 3.2 ports.',
        price: 4999,
        discountPrice: 3999,
        stock: 20,
        sku: 'COMP-DCK-03',
        searchQuery: 'usb c hub docking station',
      },
      {
        name: 'ProFold Ergonomic Aluminum Laptop Riser Stand',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Heavy-duty aircraft-grade aluminum alloy laptop stand with 360-degree rotating base, dual pivot height adjustment, and thermal cooling vents.',
        price: 1899,
        discountPrice: 1499,
        stock: 45,
        sku: 'COMP-STN-04',
        searchQuery: 'aluminum laptop stand',
      },
      {
        name: 'StreamVision 2K Quad-HD Autofocus Webcam with Privacy Shutter',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '1440p 60fps streaming webcam with wide-angle glass lens, dual noise-reducing stereo microphones, and physical magnetic privacy slider.',
        price: 3499,
        discountPrice: 2899,
        stock: 25,
        sku: 'COMP-CAM-05',
        searchQuery: 'webcam computer desk',
      },
      {
        name: 'Velocity NVMe M.2 1TB Portable External SSD 1050MB/s',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Ultra-fast shockproof portable solid state drive with USB 3.2 Gen 2 Type-C interface, aluminum heat-dissipating enclosure, and hardware encryption.',
        price: 6999,
        discountPrice: 5799,
        stock: 20,
        sku: 'COMP-SSD-06',
        searchQuery: 'portable solid state drive',
      },
      {
        name: 'Archon Wi-Fi 6 AX3000 Dual-Band Gigabit Router',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Next-generation Wi-Fi 6 router with 4 high-gain beamforming antennas, OFDMA technology, WPA3 security, and low latency for 4K streaming.',
        price: 4199,
        discountPrice: 3499,
        stock: 18,
        sku: 'COMP-RTR-07',
        searchQuery: 'wifi router modern',
      },
      {
        name: 'DeskMat XL Extended Micro-Woven Waterproof Desk Pad',
        categoryName: 'Computers & Accessories',
        categorySlug: 'computers-accessories',
        categoryKey: 'computers',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '900x400mm smooth micro-woven cloth gaming surface with non-slip natural rubber base and anti-fray stitched perimeter edges.',
        price: 999,
        discountPrice: 799,
        stock: 60,
        sku: 'COMP-MAT-08',
        searchQuery: 'extended desk pad mat',
      },

      // ----------------------------------------------------
      // 3. Men's Fashion (8 products)
      // ----------------------------------------------------
      {
        name: 'Artisan Heritage Pure French Linen Casual Shirt',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Breathable 100% natural organic French flax linen woven with a tailored regular fit, mother-of-pearl buttons, and soft garment-washed finish.',
        price: 2499,
        discountPrice: 1999,
        stock: 30,
        sku: 'MEN-SHRT-01',
        searchQuery: 'mens linen shirt',
      },
      {
        name: 'Selvedge Slim-Fit Raw Denim Jeans (14oz Japanese Cotton)',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Heavyweight unwashed raw indigo denim crafted on vintage shuttle looms with signature red selvedge id, brass rivets, and custom leather patch.',
        price: 3899,
        discountPrice: 2999,
        stock: 22,
        sku: 'MEN-JNS-02',
        searchQuery: 'raw denim jeans mens',
      },
      {
        name: 'Handcrafted Full-Grain Leather Oxford Dress Shoes',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Classic cap-toe Oxford shoes handcrafted from premium full-grain Italian leather with Goodyear welted leather soles and cushioned arch support.',
        price: 5999,
        discountPrice: 4799,
        stock: 15,
        sku: 'MEN-SHOE-03',
        searchQuery: 'mens leather dress shoes',
      },
      {
        name: 'Supima Organic Heavyweight Cotton Henley T-Shirt',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: '220 GSM combed extra-long staple Supima cotton with a 3-button placket, reinforced flatlock seams, and exceptional color retention.',
        price: 1299,
        discountPrice: 999,
        stock: 45,
        sku: 'MEN-TEE-04',
        searchQuery: 'mens henley t shirt',
      },
      {
        name: 'Vintage Aviator Polarized Sunglasses with Metal Frame',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Corrosion-resistant gold titanium alloy frame with Category 3 polarized TAC lenses offering 100% UVA/UVB protection and spring hinges.',
        price: 1799,
        discountPrice: 1399,
        stock: 35,
        sku: 'MEN-SUN-05',
        searchQuery: 'aviator sunglasses mens',
      },
      {
        name: 'Merino Wool Knit Crewneck Winter Sweater',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Ultra-fine 19.5 micron Australian Merino wool providing lightweight thermal warmth, natural odor resistance, and ribbed collar and cuffs.',
        price: 3299,
        discountPrice: 2599,
        stock: 20,
        sku: 'MEN-SWTR-06',
        searchQuery: 'merino wool sweater mens',
      },
      {
        name: 'Minimalist Bifold Leather Wallet with RFID Shielding',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Vegetable-tanned top-grain cowhide leather wallet holding up to 10 cards and cash notes with integrated metallic RFID signal blocking layer.',
        price: 1199,
        discountPrice: 899,
        stock: 50,
        sku: 'MEN-WLT-07',
        searchQuery: 'leather wallet mens',
      },
      {
        name: 'Waxed Canvas & Leather Trim Weekend Duffle Bag',
        categoryName: "Men's Fashion",
        categorySlug: 'mens-fashion',
        categoryKey: 'mens_fashion',
        brandName: 'Urban Stitch',
        vendorIndex: 1,
        description: 'Water-resistant 16oz military-grade waxed canvas travel duffle with genuine leather handles, brass hardware, and dedicated shoe compartment.',
        price: 4499,
        discountPrice: 3699,
        stock: 16,
        sku: 'MEN-BAG-08',
        searchQuery: 'waxed canvas duffle bag',
      },

      // ----------------------------------------------------
      // 4. Women's Fashion (10 products)
      // ----------------------------------------------------
      {
        name: 'Handloom Pure Mulberry Silk Zari Embroidered Saree',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Authentic Banarasi handloom silk saree handwoven with gold and silver electroplated Zari motifs. Includes unstitched matching blouse piece.',
        price: 8499,
        discountPrice: 6999,
        stock: 14,
        sku: 'WOM-SAR-01',
        searchQuery: 'silk saree handloom',
      },
      {
        name: 'Floral Chiffon Tiered Summer Maxi Dress',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Airy lightweight chiffon with hand-painted botanical prints, a smocked elastic bodice, flutter sleeves, and romantic tiered ruffle hem.',
        price: 2799,
        discountPrice: 2199,
        stock: 28,
        sku: 'WOM-DRS-02',
        searchQuery: 'floral maxi dress summer',
      },
      {
        name: 'Handcrafted Structured Leather Shoulder Tote Bag',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Pebbled full-grain leather tote with reinforced rolled shoulder straps, central zippered compartment, and protective brass bottom studs.',
        price: 4299,
        discountPrice: 3499,
        stock: 20,
        sku: 'WOM-BAG-03',
        searchQuery: 'leather tote bag womens',
      },
      {
        name: 'Anarkali Pure Chanderi Cotton Kurti Set with Dupatta',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: '3-piece ethnic festive set featuring hand-block printed Chanderi kurti with gota patti lace work, comfortable trousers, and kota doria dupatta.',
        price: 3599,
        discountPrice: 2799,
        stock: 25,
        sku: 'WOM-KRT-04',
        searchQuery: 'anarkali kurti ethnic wear',
      },
      {
        name: 'Cashmere Blend Open-Front Cardigan Wrap',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Plush Mongolian cashmere and extrafine wool blend relaxed-fit drape cardigan with deep patch pockets and ribbed cuffs.',
        price: 3199,
        discountPrice: 2499,
        stock: 22,
        sku: 'WOM-CRD-05',
        searchQuery: 'cashmere cardigan wrap',
      },
      {
        name: 'Handmade Suede Leather Block Heel Ankle Boots',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Supple kid suede leather boots with a stable 2.5-inch stacked wooden block heel, cushioned footbed, and smooth side metal zipper.',
        price: 4199,
        discountPrice: 3399,
        stock: 18,
        sku: 'WOM-BOT-06',
        searchQuery: 'suede ankle boots block heel',
      },
      {
        name: 'Sterling Silver 925 Filigree Drop Earrings',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Intricately handcrafted 925 hallmarked sterling silver dangling earrings inspired by traditional royal temple architecture.',
        price: 1699,
        discountPrice: 1299,
        stock: 35,
        sku: 'WOM-JWL-07',
        searchQuery: 'silver filigree earrings jewelry',
      },
      {
        name: 'Classic Vintage Wash Denim Trucker Jacket',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: '100% sustainable non-stretch cotton denim jacket in an authentic vintage indigo wash with dual chest flap pockets and metal shank buttons.',
        price: 2499,
        discountPrice: 1999,
        stock: 30,
        sku: 'WOM-JKT-08',
        searchQuery: 'denim jacket womens',
      },
      {
        name: 'Quilted Crossbody Clutch with Gold Chain Strap',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Diamond chevron quilted faux-leather evening clutch with turn-lock clasp closure, multi-slot interior organizer, and convertible chain strap.',
        price: 1899,
        discountPrice: 1499,
        stock: 40,
        sku: 'WOM-CLT-09',
        searchQuery: 'quilted crossbody bag clutch',
      },
      {
        name: 'Pointed-Toe Memory Foam Ballet Flats',
        categoryName: "Women's Fashion",
        categorySlug: 'womens-fashion',
        categoryKey: 'womens_fashion',
        brandName: 'Artisan Loom',
        vendorIndex: 2,
        description: 'Flexible breathable knit upper pointed flats engineered with multi-layer high-density memory foam insole and slip-resistant rubber outsole.',
        price: 1599,
        discountPrice: 1199,
        stock: 32,
        sku: 'WOM-FLT-10',
        searchQuery: 'ballet flats pointed toe',
      },

      // ----------------------------------------------------
      // 5. Home & Kitchen (12 products)
      // ----------------------------------------------------
      {
        name: 'Pre-Seasoned Heavy-Duty Cast Iron Skillet (10.5 Inch)',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Cast from pure iron ore and seasoned with 100% natural organic flaxseed oil for superior heat retention and natural non-stick searing.',
        price: 1999,
        discountPrice: 1599,
        stock: 30,
        sku: 'HOME-SKL-01',
        searchQuery: 'cast iron skillet cooking',
      },
      {
        name: 'Hand-Thrown Matte Ceramic Dinnerware Set (16 Pieces)',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Complete 4-person table service including dinner plates, salad plates, soup bowls, and mugs crafted with speckled stoneware matte glaze.',
        price: 4499,
        discountPrice: 3699,
        stock: 15,
        sku: 'HOME-DIN-02',
        searchQuery: 'ceramic dinnerware plates set',
      },
      {
        name: '15-Bar Italian Pump Stainless Steel Espresso Coffee Machine',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Professional high-pressure espresso maker with commercial milk steaming frothing wand, dual temperature control, and 1.5L removable water tank.',
        price: 9999,
        discountPrice: 7999,
        stock: 12,
        sku: 'HOME-ESP-03',
        searchQuery: 'espresso machine coffee',
      },
      {
        name: '400 Thread Count Organic Egyptian Cotton King Bedsheet Set',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Silky smooth sateen weave long-staple certified Egyptian cotton sheet set with deep 16-inch mattress pockets and 2 king pillowcases.',
        price: 2899,
        discountPrice: 2299,
        stock: 25,
        sku: 'HOME-BED-04',
        searchQuery: 'bedsheet cotton bedroom',
      },
      {
        name: 'Handcrafted Sheesham Wood Masala Dabba Spice Box (7 Containers)',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Traditional solid Indian Rosewood spice storage box with clear glass lid, 7 removable wooden spice bowls, and handmade mini brass spoon.',
        price: 1699,
        discountPrice: 1299,
        stock: 35,
        sku: 'HOME-SPC-05',
        searchQuery: 'wooden spice box kitchen',
      },
      {
        name: 'Digital Touchscreen Rapid Air Fryer 5.5L with 8 Presets',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: '360-degree rapid thermal air circulation technology allowing 85% less oil frying, non-stick dishwasher-safe basket, and LED touch controls.',
        price: 5499,
        discountPrice: 4299,
        stock: 20,
        sku: 'HOME-AFR-06',
        searchQuery: 'air fryer kitchen appliance',
      },
      {
        name: 'Ergonomic Cervical Contour Cooling Gel Memory Foam Pillow',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Orthopedic butterfly contoured neck support pillow infused with thermodynamic cooling gel layer and breathable bamboo washable cover.',
        price: 1899,
        discountPrice: 1399,
        stock: 40,
        sku: 'HOME-PLW-07',
        searchQuery: 'memory foam pillow bed',
      },
      {
        name: 'German High-Carbon Stainless Steel Chef Knife Set with Block',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: '6-piece full-tang forged German 1.4116 steel kitchen knife set with pakkawood ergonomic handles and solid pine storage block.',
        price: 3799,
        discountPrice: 2999,
        stock: 18,
        sku: 'HOME-KNF-08',
        searchQuery: 'chef knife set kitchen',
      },
      {
        name: 'Hand-Tufted Geometric Bohemian Wool Area Rug (5x7 Feet)',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Thick plush 100% natural wool pile hand-tufted by Bhadohi carpet artisans with modern Scandinavian geometric neutral patterns.',
        price: 6499,
        discountPrice: 5199,
        stock: 10,
        sku: 'HOME-RUG-09',
        searchQuery: 'wool area rug living room',
      },
      {
        name: 'Aromatherapy Natural Soy Wax Scented Candle Trio (Lavender & Oud)',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Set of 3 hand-poured pure soy wax candles in matte amber glass jars with crackling wooden wicks and 45-hour clean burn time each.',
        price: 1299,
        discountPrice: 999,
        stock: 50,
        sku: 'HOME-CND-10',
        searchQuery: 'scented soy candle amber jar',
      },
      {
        name: 'Multi-Stage UV + UF Gravity-Fed Stainless Steel Water Purifier',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Non-electric 16-liter food-grade 304 stainless steel gravity water filter with dual ceramic active carbon micro-filtration cartridges.',
        price: 3499,
        discountPrice: 2899,
        stock: 22,
        sku: 'HOME-WTR-11',
        searchQuery: 'water purifier filter kitchen',
      },
      {
        name: 'High-Speed 1200W Commercial Nutri-Blender & Smoothie Maker',
        categoryName: 'Home & Kitchen',
        categorySlug: 'home-kitchen',
        categoryKey: 'home_kitchen',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Heavy-duty 24000 RPM nutrient extractor blender with 6-leaf titanium coated extraction blades and 2 BPA-free portable travel cups.',
        price: 3899,
        discountPrice: 2999,
        stock: 26,
        sku: 'HOME-BLN-12',
        searchQuery: 'blender smoothie maker',
      },

      // ----------------------------------------------------
      // 6. Beauty & Personal Care (8 products)
      // ----------------------------------------------------
      {
        name: '2% Pure Hyaluronic Acid & B5 Deep Hydration Serum (30ml)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Multi-molecular weight hyaluronic acid serum formulated with Provitamin B5 to deliver intense multi-depth cellular skin hydration.',
        price: 799,
        discountPrice: 599,
        stock: 60,
        sku: 'BEAU-SRM-01',
        searchQuery: 'face serum skincare bottle',
      },
      {
        name: 'Cold-Pressed Moroccan Argan Oil Pure Hair & Face Elixir (100ml)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: '100% pure organic virgin unrefined Argania Spinosa oil rich in Vitamin E and essential fatty acids to tame frizz and nourish skin.',
        price: 1199,
        discountPrice: 899,
        stock: 45,
        sku: 'BEAU-OIL-02',
        searchQuery: 'argan oil cosmetic dropper',
      },
      {
        name: 'Sulfate-Free Onion & Bhringraj Anti-Hairfall Shampoo (300ml)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Ayurvedic botanical formulation infused with red onion seed extract, plant keratin, and rosemary oil to strengthen root follicles.',
        price: 599,
        discountPrice: 449,
        stock: 70,
        sku: 'BEAU-SHP-03',
        searchQuery: 'herbal shampoo bottle',
      },
      {
        name: 'Ultra-Light Invisible Sunscreen Gel SPF 50 PA++++ (50g)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Non-comedogenic water-gel broad spectrum sunscreen with zero white cast, fast absorption, and blue-light radiation defense.',
        price: 699,
        discountPrice: 549,
        stock: 55,
        sku: 'BEAU-SUN-04',
        searchQuery: 'sunscreen lotion tube',
      },
      {
        name: 'Luxury Sandalwood & Cedar Beard Grooming Kit (Oil, Balm, Comb)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Complete men grooming set in wooden gift box with cold-pressed growth oil, organic beeswax styling balm, and anti-static pearwood comb.',
        price: 1499,
        discountPrice: 1199,
        stock: 30,
        sku: 'BEAU-BRD-05',
        searchQuery: 'beard grooming kit mens',
      },
      {
        name: 'Long-Wear Velvet Matte Weightless Lipstick Set (4 Nude Shades)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Enriched with Vitamin E and jojoba oil delivering transfer-proof 12-hour comfortable pigmented matte finish without drying lips.',
        price: 1299,
        discountPrice: 999,
        stock: 40,
        sku: 'BEAU-LIP-06',
        searchQuery: 'matte lipstick cosmetics',
      },
      {
        name: 'Australian French Green Clay Purifying Detox Face Mask (100g)',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: 'Mineral-rich bentonite and French green clay mask with matcha green tea extract to draw out impurities and minimize enlarged pores.',
        price: 849,
        discountPrice: 649,
        stock: 35,
        sku: 'BEAU-MSK-07',
        searchQuery: 'clay face mask jar',
      },
      {
        name: 'Sonic Pulsating Electric Toothbrush with 4 Replacement Heads',
        categoryName: 'Beauty & Personal Care',
        categorySlug: 'beauty-personal-care',
        categoryKey: 'beauty',
        brandName: 'Botanica Herbal',
        vendorIndex: 4,
        description: '40000 micro-vibrations per minute sonic toothbrush with 5 cleaning modes, 2-minute smart quad-pacer timer, and 60-day wireless battery.',
        price: 1999,
        discountPrice: 1499,
        stock: 28,
        sku: 'BEAU-TTH-08',
        searchQuery: 'electric sonic toothbrush',
      },

      // ----------------------------------------------------
      // 7. Grocery & Food (10 products)
      // ----------------------------------------------------
      {
        name: 'Organic Certified Single-Origin Kashmir Mongra Saffron (1g)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Grade A1 pure all-red stigma Kashmiri saffron strands packed in sealed glass jar with laboratory-certified high crocin color intensity.',
        price: 649,
        discountPrice: 499,
        stock: 50,
        sku: 'GROC-SAF-01',
        searchQuery: 'saffron spice glass jar',
      },
      {
        name: 'Raw Unfiltered Wild Forest Honey (500g Glass Jar)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Ethically harvested multi-flora raw unprocessed honey straight from Himalayan alpine forests. Packed with natural bee pollen and enzymes.',
        price: 549,
        discountPrice: 429,
        stock: 65,
        sku: 'GROC-HNY-02',
        searchQuery: 'raw honey jar organic',
      },
      {
        name: 'Wood-Pressed Traditional Vedic A2 Gir Cow Ghee (500ml)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Prepared using traditional Bilona method from grass-fed indigenous Gir cow curd cultured milk, providing rich granular golden aroma.',
        price: 1199,
        discountPrice: 949,
        stock: 40,
        sku: 'GROC-GHE-03',
        searchQuery: 'clarified butter ghee jar',
      },
      {
        name: 'Single-Origin Medium Roast Arabica Whole Coffee Beans (250g)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Shade-grown specialty grade Arabica beans from Chikmagalur estates with tasting notes of dark chocolate, hazelnut, and citrus caramel.',
        price: 499,
        discountPrice: 399,
        stock: 55,
        sku: 'GROC-COF-04',
        searchQuery: 'roasted coffee beans bag',
      },
      {
        name: 'Royal Masala Chai Whole Spice CTC Black Tea (500g)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Premium Assam Orthodox CTC black tea blended with crushed green cardamom, cinnamon, cloves, black pepper, and dry ginger.',
        price: 449,
        discountPrice: 349,
        stock: 80,
        sku: 'GROC-TEA-05',
        searchQuery: 'masala chai black tea',
      },
      {
        name: 'Hand-Harvested Himalayan Fine Pink Rock Salt (1kg Pouch)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: '100% natural unrefined mineral pink salt sourced from pristine ancient sea beds containing 84 vital trace minerals.',
        price: 199,
        discountPrice: 149,
        stock: 100,
        sku: 'GROC-SLT-06',
        searchQuery: 'himalayan pink salt crystals',
      },
      {
        name: 'Cold-Pressed Extra Virgin Organic Coconut Oil (500ml)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Extracted from fresh mature coastal coconuts without chemical refining or heat, preserving rich lauric acid and fresh tropical fragrance.',
        price: 389,
        discountPrice: 299,
        stock: 60,
        sku: 'GROC-OIL-07',
        searchQuery: 'coconut oil bottle organic',
      },
      {
        name: 'Artisanal Single-Origin 72% Dark Chocolate Bars (Pack of 3)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Bean-to-bar handcrafted dark chocolate made from Kerala cocoa nibs and organic coconut sugar with zero emulsifiers or palm oil.',
        price: 599,
        discountPrice: 479,
        stock: 45,
        sku: 'GROC-CHO-08',
        searchQuery: 'artisan dark chocolate bar',
      },
      {
        name: 'California Jumbo Almonds & Walnut Kernels Mix (500g)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Vacuum-sealed premium raw non-GMO whole almonds and Chilean walnut halves rich in Omega-3 fatty acids and plant antioxidants.',
        price: 699,
        discountPrice: 549,
        stock: 50,
        sku: 'GROC-NUT-09',
        searchQuery: 'almonds walnuts dry fruits',
      },
      {
        name: 'Ancient Grain Gluten-Free Organic Rolled Oats (1kg)',
        categoryName: 'Grocery & Food',
        categorySlug: 'grocery-food',
        categoryKey: 'grocery',
        brandName: 'Himalayan Harvest',
        vendorIndex: 5,
        description: 'Whole grain thick rolled jumbo breakfast oats certified gluten-free, providing high soluble beta-glucan fiber and sustained morning energy.',
        price: 349,
        discountPrice: 269,
        stock: 75,
        sku: 'GROC-OAT-10',
        searchQuery: 'rolled oats bowl breakfast',
      },

      // ----------------------------------------------------
      // 8. Sports & Fitness (7 products)
      // ----------------------------------------------------
      {
        name: 'Quick-Select Adjustable Dumbbell Pair (2.5kg to 24kg)',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Smart dial-turn adjustable home workout dumbbells replacing 15 sets of weights with heavy-duty laser-cut steel plates and storage trays.',
        price: 14999,
        discountPrice: 11999,
        stock: 10,
        sku: 'SPRT-DMB-01',
        searchQuery: 'adjustable dumbbells gym',
      },
      {
        name: 'Extra Thick 8mm Eco-Friendly TPE Alignment Yoga Mat',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Non-slip dual texture reversible yoga mat with laser-engraved body alignment lines, carrying strap, and cushioned joint protection.',
        price: 1499,
        discountPrice: 1199,
        stock: 35,
        sku: 'SPRT-YOG-02',
        searchQuery: 'yoga mat exercise fitness',
      },
      {
        name: 'Double-Wall Vacuum Insulated Stainless Steel Gym Bottle (1000ml)',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '18/8 food-grade stainless steel sports water bottle keeping drinks ice cold for 24 hours or hot for 12 hours with leak-proof straw lid.',
        price: 999,
        discountPrice: 799,
        stock: 60,
        sku: 'SPRT-BTL-03',
        searchQuery: 'stainless steel water bottle',
      },
      {
        name: 'Latex Heavy Resistance Loop Exercise Bands Set (5 Levels)',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '100% natural Malaysian latex workout bands ranging from X-Light to X-Heavy with waterproof travel carry pouch and exercise booklet.',
        price: 799,
        discountPrice: 599,
        stock: 50,
        sku: 'SPRT-BND-04',
        searchQuery: 'resistance bands workout',
      },
      {
        name: 'Pro Speed Ball-Bearing Aluminium Cable Jump Rope',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '360-degree dual ball-bearing rotation mechanism for fast double-unders, kink-free vinyl coated steel wire, and knurled metal grip handles.',
        price: 699,
        discountPrice: 499,
        stock: 45,
        sku: 'SPRT-ROP-05',
        searchQuery: 'jump rope speed fitness',
      },
      {
        name: 'High-Density Deep Tissue Grid Foam Roller for Muscle Recovery',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Multi-density 3D matrix EVA foam roller with solid core to relieve muscle knots, enhance blood circulation, and accelerate post-workout recovery.',
        price: 1099,
        discountPrice: 849,
        stock: 30,
        sku: 'SPRT-ROL-06',
        searchQuery: 'foam roller fitness muscle',
      },
      {
        name: 'Breathable Weightlifting Gym Gloves with Integrated Wrist Wraps',
        categoryName: 'Sports & Fitness',
        categorySlug: 'sports-fitness',
        categoryKey: 'sports',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Microfiber padded palm gloves with silicone honeycomb anti-slip grip and adjustable 18-inch elastic wrist stabilization support straps.',
        price: 899,
        discountPrice: 699,
        stock: 40,
        sku: 'SPRT-GLV-07',
        searchQuery: 'gym workout gloves',
      },

      // ----------------------------------------------------
      // 9. Books & Stationery (7 products)
      // ----------------------------------------------------
      {
        name: 'Handmade Vegan Leather Hardcover Dotted Journal (160 GSM)',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Bleed-proof ultra-thick bamboo paper journal with 5mm dot grid, elastic closure band, dual ribbon page markers, and back expandable pocket.',
        price: 999,
        discountPrice: 799,
        stock: 45,
        sku: 'BOK-JRN-01',
        searchQuery: 'leather journal notebook',
      },
      {
        name: 'Vintage Solid Brass Fine Nib Fountain Pen in Gift Case',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Precision machined raw solid brass hexagonal fountain pen featuring stainless steel iridium fine nib and refillable piston ink converter.',
        price: 1699,
        discountPrice: 1299,
        stock: 30,
        sku: 'BOK-PEN-02',
        searchQuery: 'brass fountain pen vintage',
      },
      {
        name: 'Executive Undated Daily Productivity & Goal Planner',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Structured 6-month goal breakdown framework with daily time-blocking schedules, weekly reviews, habit trackers, and motivational prompts.',
        price: 1199,
        discountPrice: 899,
        stock: 40,
        sku: 'BOK-PLN-03',
        searchQuery: 'daily planner book desk',
      },
      {
        name: 'Fine Art Professional 36-Color Watercolor Paint Set with Brushes',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'High-pigment artist grade half-pan watercolors in sturdy metal travel tin with mixing palette and 3 refillable water reservoir brush pens.',
        price: 1499,
        discountPrice: 1149,
        stock: 25,
        sku: 'BOK-WTC-04',
        searchQuery: 'watercolor paint artist palette',
      },
      {
        name: 'Solid Natural Bamboo 5-Compartment Desktop Stationery Organizer',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Eco-friendly sustainable bamboo caddy designed to organize pens, markers, sticky notes, paper clips, and smartphones with clean finish.',
        price: 1299,
        discountPrice: 999,
        stock: 35,
        sku: 'BOK-ORG-05',
        searchQuery: 'bamboo desk organizer stationery',
      },
      {
        name: 'Dual-Tip Acrylic Paint Art Marker Pens (Pack of 24)',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Vibrant opaque water-based acrylic markers with 1mm extra-fine tip and 3mm medium brush tip suitable for canvas, ceramic, rock, and paper.',
        price: 1099,
        discountPrice: 849,
        stock: 30,
        sku: 'BOK-MRK-06',
        searchQuery: 'art markers pens colorful',
      },
      {
        name: 'Modern Calligraphy & Hand-Lettering Complete Beginner Kit',
        categoryName: 'Books & Stationery',
        categorySlug: 'books-stationery',
        categoryKey: 'books',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Comprehensive lettering kit including instructional guidebook, slant grid tracing sheets, 4 flexible brush pens, and black sumi ink bottle.',
        price: 1399,
        discountPrice: 1099,
        stock: 22,
        sku: 'BOK-CAL-07',
        searchQuery: 'calligraphy kit lettering',
      },

      // ----------------------------------------------------
      // 10. Toys & Games (6 products)
      // ----------------------------------------------------
      {
        name: 'Hand-Carved Wooden Tournament Chess Set with Folding Board',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: '15-inch solid Sheesham and Boxwood magnetic chess set with weighted Staunton pieces, velvet interior storage slots, and brass latch closure.',
        price: 2499,
        discountPrice: 1999,
        stock: 20,
        sku: 'TOY-CHS-01',
        searchQuery: 'wooden chess set board',
      },
      {
        name: 'Ancient World Wonder 1000-Piece Jigsaw Puzzle',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Precision-cut recycled cardboard puzzle with glare-free matte linen finish, vivid historical artwork, and included full-size reference poster.',
        price: 999,
        discountPrice: 799,
        stock: 35,
        sku: 'TOY-PZL-02',
        searchQuery: 'jigsaw puzzle pieces',
      },
      {
        name: '14-in-1 Solar Powered Educational STEM Robotics Kit',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Green energy engineering building kit allowing children to construct 14 different motorized walking and swimming robots driven by sunlight.',
        price: 1699,
        discountPrice: 1299,
        stock: 28,
        sku: 'TOY-ROB-03',
        searchQuery: 'stem robot toy kit',
      },
      {
        name: 'Classic Hardwood Tumbling Tower Block Stacking Game (54 Blocks)',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Smooth-sanded premium birchwood tumbling blocks party game with sturdy canvas storage carry bag for family game nights.',
        price: 899,
        discountPrice: 699,
        stock: 45,
        sku: 'TOY-TWR-04',
        searchQuery: 'wooden blocks stacking game',
      },
      {
        name: 'Magnetic Architecture 3D Building Tiles Set (100 Pieces)',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Translucent ultrasonic-welded magnetic geometric shapes with strong neodymium magnets promoting spatial cognitive development in children.',
        price: 2199,
        discountPrice: 1699,
        stock: 30,
        sku: 'TOY-MAG-05',
        searchQuery: 'magnetic building tiles toy',
      },
      {
        name: 'Fast-Paced Wooden Sling Puck Tabletop Board Game',
        categoryName: 'Toys & Games',
        categorySlug: 'toys-games',
        categoryKey: 'toys',
        brandName: 'Nordic Craft',
        vendorIndex: 3,
        description: 'Action hockey sling board crafted from natural pine wood with high-elastic bungee cords and 10 smooth wooden sliding pucks.',
        price: 1199,
        discountPrice: 899,
        stock: 40,
        sku: 'TOY-SLG-06',
        searchQuery: 'wooden board game tabletop',
      },

      // ----------------------------------------------------
      // 11. Automotive (6 products)
      // ----------------------------------------------------
      {
        name: 'Smart 150 PSI Digital Cordless Tire Inflator & Air Pump',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Rechargeable 6000mAh battery portable air compressor with digital pressure LCD readout, auto-shutoff preset, and built-in LED flashlight.',
        price: 3299,
        discountPrice: 2599,
        stock: 25,
        sku: 'AUTO-INF-01',
        searchQuery: 'car tire inflator pump',
      },
      {
        name: 'Dual-Lens 4K Front + 1080p Rear Dash Camera with GPS',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Ultra-wide 170-degree Sony Starvis night vision sensor, G-sensor emergency collision lock, 24-hour parking monitor, and smartphone Wi-Fi app.',
        price: 6499,
        discountPrice: 5199,
        stock: 18,
        sku: 'AUTO-DSH-02',
        searchQuery: 'car dashboard camera',
      },
      {
        name: 'Universal Magnetic Air Vent Car Phone Mount with MagSafe',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Ultra-strong N52 rare-earth magnetic matrix with 360-degree ball joint swivel and secure anti-shake steel hook vent clamp.',
        price: 999,
        discountPrice: 749,
        stock: 60,
        sku: 'AUTO-MNT-03',
        searchQuery: 'car phone mount holder',
      },
      {
        name: 'Heavy-Duty 120W Portable High-Power Car Vacuum Cleaner',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '8000 PA cyclonic suction handheld vacuum with washable HEPA filter, 16ft cigarette lighter cord, crevice nozzle, and brush attachment.',
        price: 1799,
        discountPrice: 1399,
        stock: 35,
        sku: 'AUTO-VAC-04',
        searchQuery: 'car vacuum cleaner detailing',
      },
      {
        name: 'Microfiber Plush Edgeless Car Detailing Towels (Pack of 6, 800 GSM)',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Ultra-absorbent lint-free dual-sided microfiber drying cloths designed for scratch-free washing, waxing, and ceramic coat buffing.',
        price: 899,
        discountPrice: 699,
        stock: 50,
        sku: 'AUTO-TWL-05',
        searchQuery: 'microfiber car drying towel',
      },
      {
        name: 'Dual USB-C 85W Metal Fast Car Charger Adapter (PD + QC 3.0)',
        categoryName: 'Automotive',
        categorySlug: 'automotive',
        categoryKey: 'automotive',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'All-aluminum compact flush-fit car cigarette socket adapter supporting 65W laptop charging and 20W smartphone fast charging simultaneously.',
        price: 1199,
        discountPrice: 899,
        stock: 45,
        sku: 'AUTO-CHG-06',
        searchQuery: 'car charger usb fast',
      },

      // ----------------------------------------------------
      // 12. Mobile Accessories (6 products)
      // ----------------------------------------------------
      {
        name: 'MagSafe Compatible European Full-Grain Leather Phone Case',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Supple vegetable-tanned Scandinavian leather with precision machined anodized aluminum buttons and microfiber interior lining.',
        price: 1899,
        discountPrice: 1499,
        stock: 40,
        sku: 'MOB-CAS-01',
        searchQuery: 'leather phone case cover',
      },
      {
        name: '65W GaN Fast Wall Charger with Dual Type-C & USB-A Ports',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Gallium Nitride high-efficiency compact travel power adapter capable of charging laptops, tablets, and phones with foldable AC prongs.',
        price: 2499,
        discountPrice: 1999,
        stock: 35,
        sku: 'MOB-CHG-02',
        searchQuery: 'gan fast charger wall',
      },
      {
        name: 'Heavy-Duty Braided Nylon USB-C to USB-C Cable (2-Meter, 100W)',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Tested for 25000+ bends with bulletproof aramid fiber core, aluminum alloy connectors, and built-in E-marker fast power chip.',
        price: 799,
        discountPrice: 599,
        stock: 75,
        sku: 'MOB-CBL-03',
        searchQuery: 'braided usb c cable',
      },
      {
        name: '3-in-1 Foldable Magnetic Wireless Charging Station Stand',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Simultaneous fast wireless charging dock for smartphone (15W), smartwatch (5W), and wireless earbuds (5W) with angle tilt adjustment.',
        price: 3299,
        discountPrice: 2599,
        stock: 25,
        sku: 'MOB-STN-04',
        searchQuery: 'wireless charging station stand',
      },
      {
        name: '9H Hardness Edge-to-Edge Tempered Glass Screen Protector (2-Pack)',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: 'Ultra-clear 0.33mm Japanese Asahi tempered glass with oleophobic anti-fingerprint coating and included auto-alignment installation frame.',
        price: 599,
        discountPrice: 449,
        stock: 80,
        sku: 'MOB-GLS-05',
        searchQuery: 'tempered glass screen protector',
      },
      {
        name: '10-Inch Desktop Ring Light with Extendable Tripod Stand & Phone Holder',
        categoryName: 'Mobile Accessories',
        categorySlug: 'mobile-accessories',
        categoryKey: 'mobile_accessories',
        brandName: 'Apex Audio',
        vendorIndex: 0,
        description: '120 LED high-CRI ring light with 3 color temperatures (warm, natural, cool) and 10 brightness dimming levels for video calls and content creation.',
        price: 1599,
        discountPrice: 1199,
        stock: 30,
        sku: 'MOB-RNG-06',
        searchQuery: 'ring light tripod phone',
      },
    ];

    return products;
  }

  /**
   * Execute the 100-product automated seed pipeline
   */
  static async seed100Products(onProgress?: (msg: string) => void) {
    const log = (msg: string) => {
      console.log(`[Catalog Seeder]: ${msg}`);
      if (onProgress) onProgress(msg);
    };

    log('🚀 Starting Phase 3 100-Product Catalog Pipeline...');

    // 1. Create or ensure 6 realistic Verified Vendors
    const vendorDefinitions = [
      { name: 'Apex Electronics Direct', email: 'vendor.apex@bazaarone.com', address: '101 Silicon Valley Road, Bengaluru', phone: '9876500001' },
      { name: 'Urban Stitch Clothiers', email: 'vendor.urban@bazaarone.com', address: '44 Textile Market Lane, Surat', phone: '9876500002' },
      { name: 'Artisan Loom Heritage', email: 'vendor.loom@bazaarone.com', address: '12 Silk Weaver Nagar, Kanchipuram', phone: '9876500003' },
      { name: 'Nordic Craft Living', email: 'vendor.nordic@bazaarone.com', address: '88 Timber Guild Row, Saharanpur', phone: '9876500004' },
      { name: 'Botanica Herbal Labs', email: 'vendor.botanica@bazaarone.com', address: '23 Ayurvedic Park, Haridwar', phone: '9876500005' },
      { name: 'Himalayan Harvest Estates', email: 'vendor.harvest@bazaarone.com', address: '5 Estate Ridge, Darjeeling', phone: '9876500006' },
    ];

    const passwordHash = await hashPassword('Vendor@12345');
    const createdVendors: string[] = [];

    for (const vDef of vendorDefinitions) {
      let user = await prisma.user.findUnique({ where: { email: vDef.email } });
      if (!user) {
        user = await prisma.user.create({
          data: {
            name: vDef.name,
            email: vDef.email,
            passwordHash,
            role: 'VENDOR',
            status: 'ACTIVE',
          },
        });
      }

      const slug = vDef.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const vendor = await prisma.vendor.upsert({
        where: { userId: user.id },
        update: {
          businessName: vDef.name,
          slug,
          status: 'APPROVED',
          accountStatus: 'ACTIVE',
        },
        create: {
          userId: user.id,
          businessName: vDef.name,
          slug,
          businessAddress: vDef.address,
          phone: vDef.phone,
          status: 'APPROVED',
          accountStatus: 'ACTIVE',
          rating: 4.9,
        },
      });

      createdVendors.push(vendor.id);
    }

    log(`✅ Ensured ${createdVendors.length} Verified Vendor Storefronts.`);

    // 2. Ensure all 12 Categories exist
    const categoryDefinitions = [
      { name: 'Electronics', slug: 'electronics' },
      { name: 'Computers & Accessories', slug: 'computers-accessories' },
      { name: "Men's Fashion", slug: 'mens-fashion' },
      { name: "Women's Fashion", slug: 'womens-fashion' },
      { name: 'Home & Kitchen', slug: 'home-kitchen' },
      { name: 'Beauty & Personal Care', slug: 'beauty-personal-care' },
      { name: 'Grocery & Food', slug: 'grocery-food' },
      { name: 'Sports & Fitness', slug: 'sports-fitness' },
      { name: 'Books & Stationery', slug: 'books-stationery' },
      { name: 'Toys & Games', slug: 'toys-games' },
      { name: 'Automotive', slug: 'automotive' },
      { name: 'Mobile Accessories', slug: 'mobile-accessories' },
    ];

    const categoryMap = new Map<string, string>();
    for (const cDef of categoryDefinitions) {
      const cat = await prisma.category.upsert({
        where: { slug: cDef.slug },
        update: { name: cDef.name, isActive: true },
        create: { name: cDef.name, slug: cDef.slug, isActive: true },
      });
      categoryMap.set(cDef.slug, cat.id);
    }
    log(`✅ Ensured 12 Standard Categories.`);

    // 3. Ensure Brands exist
    const brandDefinitions = ['Apex Audio', 'Urban Stitch', 'Artisan Loom', 'Nordic Craft', 'Botanica Herbal', 'Himalayan Harvest'];
    const brandMap = new Map<string, string>();
    for (const bName of brandDefinitions) {
      const bSlug = bName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const brand = await prisma.brand.upsert({
        where: { slug: bSlug },
        update: { name: bName, isActive: true },
        create: { name: bName, slug: bSlug, isActive: true },
      });
      brandMap.set(bName, brand.id);
    }

    // 4. Process all 100 Products with Pexels & Cloudinary
    const productDefs = this.get100ProductDefinitions();
    log(`📦 Seeding ${productDefs.length} products with Pexels & Cloudinary imagery...`);

    let seededCount = 0;
    for (const def of productDefs) {
      const categoryId = categoryMap.get(def.categorySlug)!;
      const brandId = brandMap.get(def.brandName);
      const vendorId = createdVendors[def.vendorIndex % createdVendors.length];
      const slug = def.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

      // Check if product already exists
      const existing = await prisma.product.findUnique({ where: { slug } });
      if (existing) {
        seededCount++;
        continue;
      }

      // Sourcing Image via Pexels API + Cloudinary
      let imageUrl: string;
      try {
        const pexelsUrl = await PexelsService.searchProductImage(def.searchQuery, def.categoryKey);
        const cloudAsset = await CloudinaryService.uploadFromUrl(pexelsUrl, 'bazaarone/catalog', `prod_${def.sku.toLowerCase()}`);
        imageUrl = cloudAsset.secureUrl || cloudAsset.url || pexelsUrl;
      } catch (err) {
        imageUrl = 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80';
      }

      await prisma.product.create({
        data: {
          vendorId,
          categoryId,
          brandId,
          name: def.name,
          slug,
          description: def.description,
          price: def.price,
          discountPrice: def.discountPrice || null,
          stock: def.stock,
          sku: def.sku,
          images: [imageUrl],
          status: 'ACTIVE',
          rating: 4.8,
          numReviews: Math.floor(Math.random() * 25) + 5,
        },
      });

      seededCount++;
      if (seededCount % 20 === 0) {
        log(`... seeded ${seededCount}/${productDefs.length} products`);
      }
    }

    log(`🎉 Successfully initialized complete 100-Product Catalog across all 12 Categories!`);
    return { count: seededCount };
  }
}
